parameters:
  #~ Default secrets for the applications - must be overridden with a secrets yaml config file not committed in you app

  #~ Database credentials
  app.secret.database.host:     'localhost'
  app.secret.database.schema:   'schema'
  app.secret.database.username: 'username'
  app.secret.database.password: 'password'

  app.token.secret.key:         'secret'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        false
    bind:
      $connectionName: 'common'
      $tokenSignatureSecretKey: '%app.token.secret.key%'

  #~ Application source code except controllers & middleware (see packages/middleware.yaml)
  Application\:
    resource: '../../src/*'
    exclude: '../../src/{Controller,Middleware,Domain}'

  #~ Application controllers
  Application\Controller\Api\:
    resource: '../../src/Controller/Api'
    public: true # services called in ControllerMiddleware
    calls:
      - [ 'setRouter', [ '@router' ] ]
      - [ 'setResponseFactory', [ '@response_factory' ] ]
      - [ 'setRequestFactory', [ '@request_factory' ] ]
      - [ 'setServerRequestFactory', [ '@server_request_factory' ] ]
      - [ 'setStreamFactory', [ '@stream_factory' ] ]
      - [ 'setUriFactory', [ '@uri_factory' ] ]

  #~ Application controllers
  Application\Domain\:
    resource: '../../src/Domain'

  #~ Application controllers
  Eureka\Component\Password\:
    resource: '../../vendor/eureka/component-password/src'

  #~ Date provider (time zone UTC & date time now UTC)
  application.date.time.zone.utc:
    class: DateTimeZone
    arguments:
      $timezone: 'UTC'

  application.date.time.now.utc:
    class: DateTimeImmutable
    arguments:
      $time: 'now'
      $timezone: '@application.date.time.zone.utc'

  DateTimeImmutable:
    alias: 'application.date.time.now.utc'
