parameters:
  #~ Default secrets for the applications - must be overridden with a secrets yaml config file not committed in you app

  #~ Database credentials
  app.secret.database.host:     'localhost'
  app.secret.database.schema:   'schema'
  app.secret.database.username: 'username'
  app.secret.database.password: 'password'

  app.token.secret.key:         'ThisIsTheDefaultSecretKeyForSignedJWT!'

services:
  # default configuration for services in *this* file
  _defaults:
    autowire:      true
    autoconfigure: true
    public:        false
    bind:
      $connectionName: 'common'

  #~ Application controllers
  Application\Controller\Api\:
    resource: '../../src/Controller/Api'
    public: true # services called in ControllerMiddleware
    calls:
      - [ 'setRouter', [ '@router' ] ]
      - [ 'setResponseFactory', [ '@response_factory' ] ]
      - [ 'setRequestFactory', [ '@request_factory' ] ]
      - [ 'setServerRequestFactory', [ '@server_request_factory' ] ]
      - [ 'setStreamFactory', [ '@stream_factory' ] ]
      - [ 'setUriFactory', [ '@uri_factory' ] ]

  #~ Application controllers
  Application\Domain\:
    resource: '../../src/Domain'

  Application\Service\LoginService: ~

  #~ Application controllers
  Eureka\Component\Password\:
    resource: '../../vendor/eureka/component-password/src'

  #~ Date provider (time zone UTC & date time now UTC)
  Lcobucci\Clock\SystemClock:
    factory: [ 'Lcobucci\Clock\SystemClock', 'fromUTC' ]

  Psr\Clock\ClockInterface:
    alias: Lcobucci\Clock\SystemClock
